library_app/urls.py
from django.urls import path


from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'), 
    path('catalogs/', views.CatalogListView.as_view(), name='catalogs'),
    path('catalog/<int:pk>', views.CatalogDetailView.as_view(), name='catalog-detail'),
]

urlpatterns += [   
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed-books'),
    path(r'borrowedbooks/', views.LoanedBooksAllListView.as_view(), name='all-borrowed-books'),
  
]

urlpatterns += [   
    path('mycatalogs/', views.LoanedCatalogsByUserListView.as_view(), name='my-borrowed-catalogs'),
    path(r'borrowedcatalogs/', views.LoanedCatalogsAllListView.as_view(), name='all-borrowed-catalogs'),   
]

urlpatterns += [
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
]

urlpatterns += [
    path('catalog/<uuid:pk>/renew/', views.renew_catalog_librarian, name='renew-catalog-librarian'),
]

urlpatterns += [
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
]

urlpatterns += [
    path('book/create/', views.BookCreate.as_view(), name='book_create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book_update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book_delete'),
]

urlpatterns += [
    path('catalog/create/', views.CatalogCreate.as_view(), name='catalog_create'),
    path('catalog/<int:pk>/update/', views.CatalogUpdate.as_view(), name='catalog_update'),
    path('catalog/<int:pk>/delete/', views.CatalogDelete.as_view(), name='catalog_delete'),
]

library_project/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.urls import path
from django.contrib import admin
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('library/', include('library_app.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

from django.views.generic import RedirectView

urlpatterns += [
    path('', RedirectView.as_view(url='/library_app/', permanent=True)),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

library_app/models.py
from django.db import models
from django.urls import reverse  


class Genre(models.Model):
    name = models.CharField(
        max_length=200,
        help_text="Book Genre"
        )

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=200,
                            help_text="Book Language")

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Description of the book")
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn'
                                      '">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Genre for this book")
   
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def display_genre(self):
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = 'Genre'

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def __str__(self):
        return self.title

class Catalog(models.Model):
    title = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.title

class Name(models.Model):
    name = models.CharField(
        max_length=200,
        help_text="Catalog Name"
        )

    def __str__(self):
        return self.name


import uuid  
from datetime import date
from django.contrib.auth.models import User  


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for book")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    LOAN_STATUS = (
        ('d', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='d',
        help_text='Book availability')

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        return f'{self.id} ({self.book.title})'


class CatalogCase(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for catalog")
    catalog = models.ForeignKey('Catalog', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    LOAN_STATUS = (
        ('d', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='d',
        help_text='Catalog availability')

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set catalog as returned"),)

    def __str__(self):
        return f'{self.id} ({self.catalog.title})'



class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

library_app/forms.py
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime  

from django import forms


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField()

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(_('You cant renew in past'))
    
        if data > datetime.date.today() + datetime.timedelta(days=30):
            raise ValidationError(
                _('You cant renew ahead'))

        return data


class RenewCatalogForm(forms.Form):
    renewal_date = forms.DateField()

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(_('You cant renew in past'))
    
        if data > datetime.date.today() + datetime.timedelta(days=7):
            raise ValidationError(
                _('You cant renew ahead'))

        return data

library_app/views.py
from django.shortcuts import render

from library_app.models import Book, Author, BookInstance, Genre, Catalog, CatalogCase

def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()    
    num_authors = Author.objects.count()
    num_catalogs = Catalog.objects.all().count()
    num_cases = CatalogCase.objects.all().count()
    num_cases_available = CatalogCase.objects.filter(status__exact='a').count() 

    
    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_catalogs': num_catalogs,
        'num_cases': num_cases,
        'num_cases_available': num_cases_available,
    }

    
    return render(request, 'index.html', context=context)

from django.views import generic

class BookListView(generic.ListView):
    model = Book
    paginate_by = 4


class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 4

class AuthorDetailView(generic.DetailView):
    model = Author

class CatalogListView(generic.ListView):
    model = Catalog
    paginate_by = 4

class CatalogDetailView(generic.DetailView):
    model = Catalog


from django.contrib.auth.mixins import LoginRequiredMixin


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'library_app/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


class LoanedCatalogsByUserListView(LoginRequiredMixin, generic.ListView):
    model = CatalogCase
    template_name = 'library_app/catalogcase_list_borrowed_user.html'

def get_queryset(self):
        return CatalogCase.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')



from django.contrib.auth.mixins import PermissionRequiredMixin


class LoanedBooksAllListView(PermissionRequiredMixin, generic.ListView):
    model = BookInstance
    permission_required = 'library.can_mark_returned'
    template_name = 'library_app/bookinstance_list_borrowed_all.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')   


class LoanedCatalogsAllListView(PermissionRequiredMixin, generic.ListView):
    model = CatalogCase
    permission_required = 'library.can_mark_returned'
    template_name = 'library_app/catalogcase_list_borrowed_all.html'
    paginate_by = 10

def get_queryset(self):
        return CatalogCase.objects.filter(status__exact='o').order_by('due_back')

from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime
from django.contrib.auth.decorators import permission_required

from library_app.forms import RenewBookForm
from library_app.forms import RenewCatalogForm

@permission_required('library.can_mark_returned')
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)
    if request.method == 'POST':
        form = RenewBookForm(request.POST)
        if form.is_valid():
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            return HttpResponseRedirect(reverse('all-borrowed-books'))
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(days=30)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'library_app/book_renew_librarian.html', context)

@permission_required('library.can_mark_returned')
def renew_catalog_librarian(request, pk):
    catalog_case = get_object_or_404(CatalogCase, pk=pk)
    if request.method == 'POST':
        form = RenewCatalogForm(request.POST)
        if form.is_valid():
            catalog_case.due_back = form.cleaned_data['renewal_date']
            catalog_case.save()

            return HttpResponseRedirect(reverse('all-borrowed-catalogs'))
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(days=30)
        form = RenewCatalogForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'catalog_case': catalog_case,
    }

    return render(request, 'library_app/catalog_renew_librarian.html', context)


from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Author


class AuthorCreate(PermissionRequiredMixin, CreateView):
    model = Author
    fields = '__all__'
    initial = {'date_of_death': '05/01/2018'}
    permission_required = 'library.can_mark_returned'


class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    permission_required = 'library.can_mark_returned'


class AuthorDelete(PermissionRequiredMixin, DeleteView):
    model = Author
    success_url = reverse_lazy('authors')
    permission_required = 'library.can_mark_returned'


class BookCreate(PermissionRequiredMixin, CreateView):
    model = Book
    fields = '__all__'
    permission_required = 'library.can_mark_returned'


class BookUpdate(PermissionRequiredMixin, UpdateView):
    model = Book
    fields = '__all__'
    permission_required = 'library.can_mark_returned'


class BookDelete(PermissionRequiredMixin, DeleteView):
    model = Book
    success_url = reverse_lazy('books')
    permission_required = 'library.can_mark_returned'




class CatalogCreate(PermissionRequiredMixin, CreateView):
    model = Catalog
    fields = '__all__'
    permission_required = 'library.can_mark_returned'


class CatalogUpdate(PermissionRequiredMixin, UpdateView):
    model = Catalog
    fields = '__all__'
    permission_required = 'library.can_mark_returned'


class CatalogDelete(PermissionRequiredMixin, DeleteView):
    model = Catalog
    success_url = reverse_lazy('catalogs')
    permission_required = 'library.can_mark_returned'

library_app/templates/library_app/author_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Deleting author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

library_app/templates/library_app/author_detail.html
{% extends "base.html" %}

{% block content %}

<h1> {{ author }} </h1>

<div class="container">
<p>{{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %}</p>
<div style="margin-left:20px;margin-top:20px">
<h3>Books</h3>
<hr/>
<dl>
{% for book in author.book_set.all %}
  <dt><a href="{% url 'book-detail' book.pk %}">{{book}}</a> ({{book.bookinstance_set.all.count}})</dt>
  <dd>{{book.summary}}</dd>
{% endfor %}
</dl>
</div>
</div>
{% endblock %}

library_app/templates/library_app/author_form.html
{% extends "base.html" %}

{% block content %}

<h1>Create Author</h1>

<div class = "container">

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
</div>
{% endblock %}

library_app/templates/library_app/author_list.html
{% extends "base.html" %}
{% block content %}
<h1>Author List</h1>
{% if author_list %}
<div class="container">
<h2>Status :</h2>
<hr />
  {% for author in author_list %}
<p><a href="{{ author.get_absolute_url }}">
      {{ author }} ({{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %})
      </a></p>
  {% endfor %}
{% else %}
  <p>There are no authors available.</p>
{% endif %}
</div>              
{% endblock %}

library_app/templates/library_app/book_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Deleting book: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

library_app/templates/library_app/book_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ book.title }}</h1>

  <div class = "container">
  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> 
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Language:</strong> {{ book.language }}</p>  
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>  
  </div>

<div class = "container-1">
  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
      </div>
    {% endfor %}
  </div>
{% endblock %}

library_app/templates/library_app/book_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Book List</h1>
  {% if book_list %}
<div class="container">
<h2>Status :</h2>
   <hr />
    {% for book in book_list %}
       <p> <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})</p>
    {% endfor %}

</div>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}       
{% endblock %}

library_app/templates/library_app/bookinstance_list_borrowed_user.html
{% extends "base.html" %}

{% block content %}
    <h1> Borrowed books</h1>

    <div class = "container">

    {% if bookinstance_list %}
    
      {% for bookinst in bookinstance_list %} 
      <div class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </div>
      {% endfor %}
 

    {% else %}
      <p>No books borrowed.</p>
    {% endif %}
    </div>       
{% endblock %}

library_app/templates/library_app/catalog_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Delete Catalog</h1>

<p>Deleting catalog: {{ catalog }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

library_app/templates/library_app/catalog_form.html
{% extends "base.html" %}

{% block content %}

<h1>Create Catalog</h1>

<div class = "container">
<form action="" method="post">


    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
</div>
{% endblock %}

library_app/templates/library_app/catalog_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Catalog List</h1>
  {% if catalog_list %}
<div class="container">
<h2>Status :</h2>
   <hr />
    {% for catalog in catalog_list %}
       <p> <a href="{{ catalog.get_absolute_url }}">{{ catalog.title }}</a></p>
    {% endfor %}

</div>
  {% else %}
    <p>There are no catalogs in the library.</p>
  {% endif %}       
{% endblock %}

library_app/templates/library_app/catalog_renew_librarian.html
{% extends "base.html" %}

{% block content %}
    <h1>{{catalog_case.catalog.title}}</h1>
    <div class = "container">
    <p>Borrower: {{catalog_case.borrower}}</p>
    <p{% if catalog_case.is_overdue %} class="text-danger"{% endif %}>Due date: {{catalog_case.due_back}}</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>
    </div>
{% endblock %}

library_app/templates/library_app/catalogcase_list_borrowed_all.html
{% extends "base.html" %}

{% block content %}
    <h1>Borrowed Catalogs</h1>
     
     <div class = "container">
    
    {% if  catalogcase_list %}
    
      {% for catalogcase in catalogcase_list %} 
      <div class="{% if catalogcase.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'catalog-detail' catalogcase.catalog.pk %}">
        {{catalogcase.catalog.title}}</a> ({{ catalogcase.due_back }}) 
        {% if user.is_staff %}- {{ catalogcase.borrower }}{% endif %}
         {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-catalog-librarian' catalogcase.id %}">Renew</a> 
          {% endif %}
      </div>
     
      {% endfor %} 

    {% else %}
      <p>No catalogs.</p>
    {% endif %}    
    </div>   
{% endblock %}

library_app/templates/library_app/catalogcase_list_borrowed_user.html
{% extends "base.html" %}

{% block content %}
    <h1> Borrowed catalogs</h1>

    <div class = "container">

    {% if catalogcase_list %}
    
      {% for catalogcase in catalogcase_list %} 
      <div class="{% if catalogcase.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'catalog-detail' catalogcase.catalog.pk %}">{{catalogcase.catalog.title}}</a> ({{ catalogcase.due_back }})        
      </div>
      {% endfor %}
 

    {% else %}
      <p>No catalogs.</p>
    {% endif %}
    </div>       
{% endblock %}